### ISSUE TITLE
Unable to convert the onnx model to nnoir

### ISSUE THREAD

**Issue by nixondutt** [Idein/nnoir#126]
Tensorflow model = https://hub.tensorflow.google.cn/tensorflow/ssd_mobilenet_v2/fpnlite_640x640/1
Pipeline - tfmodel -> tflite(export_tflite_graph_tf2.py) -> onnx ->nnoir. 
![nnoir_conversion_error](https://user-images.githubusercontent.com/17126178/132446913-33513823-ee12-4095-810e-84a9b4a89756.png)

**Comment by ishiy1993** [comment]
nnoir does not support `Cast`.
Please extract the subgraph which has no unsupported operators and convert it to nnoir.
The [onnigiri](https://pypi.org/project/onnigiri/) is a tool to extract the subgraph from onnx.

There are some examples which convert other tensorflow models to nnoir in [this repository](https://github.com/Idein/tensorflow-object-detection-api-to-nnoir).
It may be helpful.

**Comment by ishiy1993** [comment]
[The latest onnx2nnoir](https://pypi.org/project/nnoir-onnx/) shows operators that are not supported when the conversion fails.
It is helpful to extract the subgraph.

**Comment by nixondutt** [comment]
Thank you for the answer. I have tried few models from tf2 detection zoo (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) with no luck. 
Do you happen to know few models which have all the supported operators?
What I am looking for is to convert a detection model to NNOIR format of Image size(640*640)

**Comment by nixondutt** [comment]
Thank you for the answer. I have tried few models from tf2 detection zoo (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) with no luck.
Do you happen to know few subgraphs which have all the supported operators?
What I am looking for is to convert a detection model to NNOIR format of Image size(640*640)

**Comment by ishiy1993** [comment]
> Do you happen to know few subgraphs which have all the supported operators?

I don't know.
If you upload the `model.onnx.dot` file which the latest onnx2nnoir(version>=1.0.14) generates, I may be able to give you some advice.

**Comment by nixondutt** [comment]
I could extract a subgraph from tf1_detection_zoo(http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz) which works. 

About the model.onnx.dot file, the uploaded model.onnx.dot file is the one with the `cast` operator issue.  (https://hub.tensorflow.google.cn/tensorflow/ssd_mobilenet_v2/fpnlite_640x640/1)
[model.onnx.docx](https://github.com/Idein/nnoir/files/7141291/model.onnx.docx)

**Comment by ishiy1993** [comment]
> model.onnx.docx

Please upload a text file not Word file.

**Comment by nixondutt** [comment]
> Please upload a text file not Word file.
[model.onnx.txt](https://github.com/Idein/nnoir/files/7141371/model.onnx.txt)

**Comment by ishiy1993** [comment]
Please try:

```
pip install onnigiri
onnigiri model.onnx -o model_main.onnx --from 'serving_default_input:0' --to 'convert_scores' 'Div__994:0'
onnx2nnoir -o model_main.nnoir model_main.onnx --graph_name ssd_model_main_640
```

**Comment by nixondutt** [comment]
This solves the problem. Thank you very much for the help. I am closing the issue.
