### ISSUE TITLE
onnx2nnoir: command not found after installation

### ISSUE THREAD

**Issue by samiul-gtmi** [Idein/nnoir#146]
I've downloaded an ```.onnx``` model (https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet50-v2-7.onnx) and trying to convert in to ```.nnoir``` format. I've renamed the file to ```model.onnx``` and trying to convert it using the command lines given in the **Example** section of the library description(https://pypi.org/project/nnoir-onnx/). 
But the command lines are being problematic so I am not being able to convert the model to ```.nnoir``` format. 
The logs are attached as a ```.txt``` file.
[onnx-nnoir.txt](https://github.com/Idein/nnoir/files/9177835/onnx-nnoir.txt)

Kindly let me know how to solve this.

**Comment by ishiy1993** [comment]
Try:

```
$ export PATH=$PATH:~/.local/bin
$ onnx2nnoir -o model.nnoir model.onnx
```

**Comment by samiul-gtmi** [comment]
This works. Thank you very much.
