### ISSUE TITLE
Error: This ONNX model includes dimension variables.

### ISSUE THREAD

**Issue by samiul-gtmi** [Idein/nnoir#147]
I converted my model from HDF5 to .onnx format using tf2onnx library. And hence, I want to further convert it into .nnoir format using onnx2nnoir. My onnx model name is **tm1.onnx** and I wanted to convert it to **tm1.nnoir** using the following command - 
```onnx2nnoir -o tm1.nnoir tm1.onnx```. But I am getting the following error:
```
Error: This ONNX model includes dimension variables.
{'unk__6'}
Set the values with the `--fix_dimension` option.
```
I understood that I should fix the dimension value, but I have found no guidelines to instruct me so. I entered some values in the command using ```--fix_dimension``` keyword, but it was not fruitful as it shows ```onnx2nnoir: error: argument --fix_dimension: invalid parse_assign value:``` error. 
I will be really grateful if someone can guide me on this.

**Comment by ishiy1993** [comment]
Try:

```
onnx2nnoir -o tm1.nnoir --fix_dimension unk__6=1 tm1.onnx
```

I'm not sure if `unk__6=1` is reasonable. Use a reasonable value and try.

Ref:

https://github.com/Idein/nnoir/blob/881f3b81efc953b1aee5b091b4fd58e7df392dac/nnoir-onnx/example/super_resolution/Makefile#L7

**Comment by samiul-gtmi** [comment]
Thank you very much for the reply.
