### ISSUE TITLE
Unable to install with Python 3.10.4

### ISSUE THREAD

**Issue by TakedaHiromasa** [Idein/nnoir#153]
actdkのv1.13.0でサポートプラットフォームに Ubuntu 22.04が追加されましたが、
Ubuntu 22.04 LTSにデフォルトで入っているPython3.10.4ではnnoir-onnxがインストールできませんでした。
Python3.8.14にダウングレードしたところインストールできました。

インストールコマンドは以下です。
```
$ python3 -V
Python 3.10.6

$ pip3 --version
pip 22.2.2 from /home/<user>/.local/lib/python3.10/site-packages/pip (python 3.10)

$ pip3 install nnoir-onnx
```

エラーログは以下です。
[log.txt](https://github.com/Idein/nnoir/files/9671754/log.txt)

**Comment by TakedaHiromasa** [comment]
Hmmm...
It's hard to make a decision to choose one over the other.
The standard Python version on Ubuntu 20.04LTS is Python 3.8.2, so it seems fine.
https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Python3_by_default

But the standard Python version of Ubuntu18.04LTS is Python 3.6, I believe...
I will wait for Ubuntu 18.04 to be no longer supported.

**Comment by ishiy1993** [comment]
Please use docker image.

https://github.com/Idein/nnoir/tree/master/nnoir-onnx#example
